# Generated by Django 5.2.6 on 2025-09-22 17:17

from django.db import migrations, models
import django.core.validators

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('guest_number', models.IntegerField(
                    validators=[django.core.validators.MinValueValidator(2),
                                django.core.validators.MaxValueValidator(20)]
                )),
                ('special_requests_comments', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),  
                ('email', models.EmailField(max_length=254)),        
                # ('reservation_active', models.BooleanField(default=True)),
                ('assigned_date_YYYY_MM_DD', models.DateTimeField(null=True, blank=True)),  
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('inventory', models.IntegerField()),
            ],
        ),
    ]
