# Generated by Django 5.2.6 on 2025-09-30 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_menu_inventory_menu_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='assigned_date_YYYY_MM_DD',
            new_name='assigned_date',
        ),
    ]
