# Generated by Django 5.2.6 on 2025-09-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_assigned_date_yyyy_mm_dd_booking_assigned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_active',
            field=models.BooleanField(default=True),
        ),
    ]
