# Generated by Django 5.2.6 on 2025-10-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_booking_reservation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
