# Generated by Django 5.2.6 on 2025-10-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_booking_number_of_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
